### ISSUE TITLE
Why Ping() function doesn't work?

### ISSUE THREAD

**Issue by deslum** [lib/pq#834]
I am trying to display the text of error when the database becomes inaccessible while program is running. First I launch the database container, then run a go-program. Program checks connection in the infinite loop and prints "Connected" if database available. I use Ping() function to check it. Then, while the program is running, I stop docker-container to imitate the inaccessibility of the database. But the program continues to print text "Connected". Why Ping() function doesn't return error?

go version **go1.11.5 linux/amd64**
database **postgres 9.6**

**docker-compose.yml**

```
version: '2'

services:
  db:
    image: postgres:9.6
    ports:
      - 766:5432
    environment:
      - POSTGRES_USER=notifications
      - POSTGRES_PASSWORD=12345
      - PGDATA=/var/lib/postgresql/data/pgdata

```

**main.go**

```
package main

import (
        "time"
        "fmt"
        "database/sql"
        _ "github.com/lib/pq"
)

func main() {
        db, err := sql.Open("postgres", "postgres://notifications:12345@localhost:766/notifications?sslmode=disable")
        if err != nil {
                fmt.Println(err)
                return
        }

        for {
                pingErr := db.Ping()
                if pingErr != nil {
                        fmt.Println(pingErr)
                } else {
                        fmt.Println("Connected")
                }
                time.Sleep(time.Duration(3) * time.Second)
        }
}

```
